export enum EOrgChartTypes   {
    'SET_IS_LOADING' = 'SET_IS_LOADING',
    'SET_HAS_ERROR' = 'SET_HAS_ERROR',
    'SET_CURRENT_USER' = 'SET_CURRENT_USER',
    'SET_RENDER_MANAGERS' = 'SET_RENDER_MANAGERS',
    'SET_REDNDER_SEARCH_INFO' = 'SET_REDNDER_SEARCH_INFO',
    'SET_SEARCH_QUERY' = 'SET_SEARCH_QUERY' 
  }
  